### ISSUE TITLE
[Social Color Variables] Youtube has changed color!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/building-blocks#197]
Same like github, Youtube has changed there site and color to black!
Do we need to update youtube color variables ??
The color is => **#232323** aka rgb(35,35,35)

![screenshot from 2017-05-04 20-14-52](https://cloud.githubusercontent.com/assets/4970624/25709449/081f1b2e-3107-11e7-9deb-ea755658eac8.png)

**Comment by IamManchanda** [comment]
- [ ] [Social Buttons](http://foundation.zurb.com/building-blocks/blocks/social-buttons.html)
- [ ] [Rounded Social Buttons](http://foundation.zurb.com/building-blocks/blocks/rounded-social-buttons.html) 
- [ ] [Sticky Social Bar](http://foundation.zurb.com/building-blocks/blocks/sticky-social-bar.html)

**Comment by Deckluhm** [comment]
No, YouTube is still red, the top-bar is only dark-gray on video pages (for better immersion I guess).

**Comment by IamManchanda** [comment]
I will keep this PR open 
coz they are currently working on the design
We might need to change then!

**Comment by Deckluhm** [comment]
Because new website designs are always cool, you may still have the "old" YouTube design and want to try the new one: https://www.youtube.com/new

And here is the official blog post about this redesign: https://youtube.googleblog.com/2017/05/a-sneak-peek-at-youtubes-new-look-and.html

@IamManchanda I highly doubt they are going to change the whole YouTube identity (from red to dark-gray) but we can wait for the final design announcement to close this issue!

**Comment by IamManchanda** [comment]
Only thing i can say right now is .... coming from dark sublime backgrounds 
i am just loving the youtube new design => https://i.imgur.com/l9e2qYU.png

**Comment by IamManchanda** [comment]
Youtube Dark in here, https://www.youtube.com/yt/brand/color.html
But still closing this as i dont think, we need a color change!
