### ISSUE TITLE
ROUND FOUNDATION ICONS

### ISSUE THREAD

**Issue by blynnc** [zurb/building-blocks#228]
THE NEW FOUNDATION ICON SETS ARE NICE.  HOWEVER THERE SHOULD BE ROUND ONES.

IF I AM RIDING A BICYCLE - I CAN'T DO IT WITH WHEELS THAT ONLY HAVE SLIGHTLY ROUNDED CORNERS.

**Comment by Deckluhm** [comment]
Unless I missed something, Foundation Icons hasn't been updated for years ([zurb/foundation-icon-fonts](https://github.com/zurb/foundation-icon-fonts), [zurb/foundation-icons](https://github.com/zurb/foundation-icons)) and seems to be an abandoned project.

If you are interested by icons font to use for Building Blocks, you should check this discussion: https://github.com/zurb/building-blocks/issues/217 (which basically talks about official fonts icon recommandation and [Font Awesome](http://fontawesome.io)).

I personally really like [Ionicons](http://ionicons.com) (official icons font from the [Ionic Framework](http://ionicframework.com) which can be used independently) because it offers 3 variations of every icon (+ brands icons).

**Comment by rafibomb** [comment]
@blynnc True - these are Building Blocks using FontAwesome which is the most popular icon set I know of.

A vimeo icon exists in their library and since this is open source, anyone can add it. Are you able to do a pull request to add it?

**Comment by rafibomb** [comment]
@blynnc Is that what you're looking for? http://foundation.zurb.com/building-blocks/blocks/rounded-social-buttons.html
